export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAN_MSG = "CLEAN_MSG";
export const SHOW_ERROR_MSG = "SHOW_ERROR_MSG";
export const SHOW_INFO_MSG = "SHOW_INFO_MSG";
export const SHOW_SUCCESS_MSG = "SHOW_SUCCESS_MSG";
export const FETCH_USER_APPOINTMENTS_SUCCESS =
  "FETCH_USER_APPOINTMENTS_SUCCESS";
export const FETCH_USER_APPOINTMENTS_FAIL = "FETCH_USER_APPOINTMENTS_FAIL";
export const SELECT_APPOINTMENT = "SELECT_APPOINTMENT";
export const LOADING = "LOADING";
export const REMOVE_APPOINTMENT_FAIL = "REMOVE_APPOINTMENT_FAIL";
export const REMOVE_APPOINTMENT_SUCCESS = "REMOVE_APPOINTMENT_SUCCESS";
